/* Data Schema */

-- SCHEMA: data_23

-- DROP SCHEMA IF EXISTS data_23 ;

CREATE SCHEMA IF NOT EXISTS data_23
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA data_23 TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_23
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_23
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_23
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_23
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;
